import { useMemo, useState } from 'react'
import TileState from './TileState'
import type { EventsData } from './types'

const clock=(value:string)=>new Intl.DateTimeFormat('de-AT',{timeZone:'Europe/Vienna',hour:'2-digit',minute:'2-digit'}).format(new Date(value))
const dateKey=(value:Date|string)=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Vienna',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(value))
const categoryFilters:Record<string,string>={Konzerte:'Konzert',Theater:'Theater',Film:'Film',Ausstellung:'Ausstellung',Festival:'Festival',Club:'Club'}

export default function EventsTile({data,loading,error,onShowAll}:{data?:EventsData;loading:boolean;error?:string|null;onShowAll:()=>void}) {
  const [filter,setFilter]=useState('Heute')
  const events=useMemo(()=>{if(!data)return[];const now=new Date();const tomorrow=new Date(now.getTime()+86_400_000);return data.events.filter(event=>{const eventDate=new Date(event.start);if(filter==='Heute')return dateKey(eventDate)===dateKey(now);if(filter==='Morgen')return dateKey(eventDate)===dateKey(tomorrow);if(filter==='Wochenende')return [0,6].includes(Number(new Intl.DateTimeFormat('en',{timeZone:'Europe/Vienna',weekday:'short'}).format(eventDate)==='Sun'?0:new Intl.DateTimeFormat('en',{timeZone:'Europe/Vienna',weekday:'short'}).format(eventDate)==='Sat'?6:-1));if(filter==='In meiner Nähe')return event.distanceKm!==null;if(filter==='Kostenlos')return event.priceType==='free';return event.category===categoryFilters[filter]}).sort((a,b)=>new Date(a.start).getTime()-new Date(b.start).getTime())},[data,filter])
  return <article className="wien-tile events-tile"><div className="wien-tile-head"><div><span className="wien-eyebrow">HEUTE IN WIEN</span><h2>Was läuft?</h2></div><button className="text-button" onClick={onShowAll}>Alle Events</button></div><div className="event-filters" aria-label="Eventfilter">{['Heute','Morgen','Wochenende','Konzerte','Theater','Film','Ausstellung','Festival','Club','Kostenlos','In meiner Nähe'].map(item=><button key={item} className={filter===item?'active':''} onClick={()=>setFilter(item)}>{item}</button>)}</div><TileState loading={loading} error={error} notice={data?.notice} mock={data?.state==='mock'}/>{data&&<div className="event-list">{events.slice(0,5).map(event=><a key={event.id} href={event.sourceUrl||undefined} onClick={event.sourceUrl?undefined:e=>e.preventDefault()} target={event.sourceUrl?'_blank':undefined} rel="noreferrer"><time>{clock(event.start)}</time><div><strong>{event.title}</strong><span>{event.venue}{event.district?` · ${event.district}. Bezirk`:''}{event.distanceKm!==null?` · ${event.distanceKm} km`:''}</span></div><em>{event.priceType==='free'?'Kostenlos':event.category}</em></a>)}{events.length===0&&<div className="wien-empty">Keine passenden Events in dieser Datenquelle.</div>}</div>}</article>
}
