export interface Departure { plannedTime: string; realTime: string | null; countdown: number; delayMinutes: number }
export interface TransitDirection { line: string; towards: string; direction: string; platform?: string; departures: Departure[]; actualIntervalMinutes: number | null }
export interface TransitData { state: string; source: string; station: { diva: string; name: string; latitude: number; longitude: number; permanent: boolean }; directions: TransitDirection[]; disruptions: string[]; updatedAt: string; notice?: string }
export interface TrafficData { state: string; configured: boolean; provider: string | null; route: { start: string; destination: string }; currentMinutes: number | null; normalMinutes: number | null; delayMinutes: number | null; status: string; incidents: Array<{ type: string; description: string; from?: string; to?: string }>; map?: { enabled: boolean; provider: 'google'; browserApiKey: string | null; start: { lat: number; lng: number }; destination: { lat: number; lng: number }; encodedPolyline: string | null }; updatedAt: string; notice?: string }
export interface WeatherHour { time: string; temperature: number; precipitationProbability: number; precipitation: number; weatherCode: number }
export interface WeatherData { state: string; source: string; location: { name: string; latitude: number; longitude: number }; temperature: number; apparentTemperature: number; weatherCode: number; condition: string; precipitationProbability: number; nextHourPrecipitation: number; windSpeed: number; high: number; low: number; sunset: string; warning: string | null; hourly: WeatherHour[]; updatedAt: string; notice?: string }
export interface ViennaEvent { id: string; title: string; start: string; end: string | null; venue: string; district: number | null; category: string; priceType: 'free' | 'paid' | 'unknown'; imageUrl: string | null; sourceName: string; sourceUrl: string | null; distanceKm: number | null; isMock: boolean }
export interface EventsData { state: string; configured: boolean; source: string; events: ViennaEvent[]; updatedAt: string; notice?: string }
export interface WienDashboardData { transit?: TransitData; traffic?: TrafficData; weather?: WeatherData; events?: EventsData; updatedAt: string }
export interface FavoriteStation { diva: string; name: string; line: string; direction: string }
export interface WienSettings { favorites: FavoriteStation[]; trafficStart: string; trafficDestination: string; preferredRoute: string; tollRoads: boolean; motorways: boolean; trafficInterval: number; weatherLat: number; weatherLon: number; eventRadius: number; eventCategories: string[]; autoRefresh: boolean; transitInterval: number; weatherInterval: number; eventsInterval: number; hourFormat: '12' | '24'; density: 'compact' | 'large' }
export interface TileProps<T> { data?: T; loading: boolean; error?: string | null; stale?: boolean }
