import { useCallback, useEffect, useMemo, useState } from 'react'
import TransitTile from './TransitTile'
import TrafficTile from './TrafficTile'
import WeatherTile from './WeatherTile'
import EventsTile from './EventsTile'
import WienSettingsPanel from './WienSettingsPanel'
import type { TransitData, WienDashboardData, WienSettings } from './types'
import '../../styles/WienLive.css'

const STORAGE_KEY='hackerboard-wien-live-settings-v1'
const defaults:WienSettings={favorites:[],trafficStart:'Donaumarina, Wien',trafficDestination:'Wiener Neustadt Zentrum',preferredRoute:'A23',tollRoads:true,motorways:true,trafficInterval:180,weatherLat:48.2061223,weatherLon:16.4309681,eventRadius:10,eventCategories:[],autoRefresh:true,transitInterval:25,weatherInterval:600,eventsInterval:1800,hourFormat:'24',density:'compact'}
function loadSettings(){try{return {...defaults,...JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}}catch{return defaults}}

export default function WienLiveDashboard(){
  const [settings,setSettings]=useState<WienSettings>(loadSettings);const [data,setData]=useState<WienDashboardData|null>(null);const [favorites,setFavorites]=useState<Record<string,TransitData>>({});const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const [offline,setOffline]=useState(!navigator.onLine);const [showSettings,setShowSettings]=useState(false);const [showAllEvents,setShowAllEvents]=useState(false)
  const params=useMemo(()=>new URLSearchParams({start:settings.trafficStart,destination:settings.trafficDestination,motorways:String(settings.motorways),tollRoads:String(settings.tollRoads),weatherLat:String(settings.weatherLat),weatherLon:String(settings.weatherLon)}).toString(),[settings])
  const refresh=useCallback(async(signal?:AbortSignal)=>{setError(null);try{const response=await fetch(`/api/wien/dashboard?${params}`,{signal});if(!response.ok)throw new Error(`Dashboard API ${response.status}`);const next=await response.json();setData(next);const results=await Promise.allSettled(settings.favorites.map(async favorite=>{const item=await fetch(`/api/wien/transit/departures?diva=${encodeURIComponent(favorite.diva)}&line=${encodeURIComponent(favorite.line)}`,{signal});if(!item.ok)throw new Error(`${favorite.name}: API ${item.status}`);return [favorite.diva,await item.json()] as const}));const mapped:Record<string,TransitData>={};results.forEach(result=>{if(result.status==='fulfilled')mapped[result.value[0]]=result.value[1]});setFavorites(mapped)}catch(reason){if((reason as Error).name!=='AbortError')setError((reason as Error).message||'Wien Live nicht erreichbar')}finally{setLoading(false)}},[params,settings.favorites])
  useEffect(()=>{const controller=new AbortController();setLoading(true);refresh(controller.signal);return()=>controller.abort()},[refresh])
  useEffect(()=>{if(!settings.autoRefresh)return;const timer=window.setInterval(()=>refresh(),Math.max(20,settings.transitInterval)*1000);return()=>window.clearInterval(timer)},[refresh,settings.autoRefresh,settings.transitInterval])
  useEffect(()=>{const online=()=>{setOffline(false);refresh()};const offlineHandler=()=>setOffline(true);window.addEventListener('online',online);window.addEventListener('offline',offlineHandler);return()=>{window.removeEventListener('online',online);window.removeEventListener('offline',offlineHandler)}},[refresh])
  const saveSettings=(next:WienSettings)=>{setSettings(next);localStorage.setItem(STORAGE_KEY,JSON.stringify(next))}
  return <div className={`wien-live ${settings.density}`}><div className="wien-live-header"><div><span className="wien-eyebrow">EUROPE/VIENNA · LIVE ÜBERBLICK</span><h1>Wien Live</h1></div><div className="wien-actions">{offline&&<span className="offline-badge">OFFLINE</span>}<button onClick={()=>refresh()} aria-label="Wien Live aktualisieren">↻ Aktualisieren</button><button onClick={()=>setShowSettings(true)} aria-label="Wien Live Einstellungen öffnen">⚙ Einstellungen</button></div></div>{error&&data&&<div className="stale-banner" role="alert">⚠ Daten möglicherweise nicht aktuell · {error}</div>}<div className="wien-grid"><TransitTile data={data?.transit} loading={loading&&!data} error={!data?error:null} permanent hour12={settings.hourFormat==='12'}/><TrafficTile data={data?.traffic} loading={loading&&!data} error={!data?error:null}/><WeatherTile data={data?.weather} loading={loading&&!data} error={!data?error:null}/><EventsTile data={data?.events?{...data.events,events:showAllEvents?data.events.events:data.events.events.slice(0,5)}:undefined} loading={loading&&!data} error={!data?error:null} onShowAll={()=>setShowAllEvents(value=>!value)}/></div>{settings.favorites.length>0&&<section className="favorite-transit"><div className="subsection-head"><div><span className="wien-eyebrow">DEINE FAVORITEN</span><h2>Weitere Haltestellen</h2></div></div><div className="favorite-grid">{settings.favorites.map(favorite=>{const favoriteData=favorites[favorite.diva];const filtered=favoriteData?{...favoriteData,directions:favorite.direction==='both'?favoriteData.directions:favoriteData.directions.filter(item=>item.direction===favorite.direction)}:undefined;return <TransitTile key={favorite.diva} data={filtered} loading={loading&&!favoriteData} error={!favoriteData&&!loading?'Haltestelle aktuell nicht verfügbar':null} compact hour12={settings.hourFormat==='12'}/>})}</div></section>}{showSettings&&<WienSettingsPanel settings={settings} onChange={saveSettings} onClose={()=>setShowSettings(false)}/>}</div>
}
