import { useEffect, useState } from 'react'
import type { WienSettings } from './types'

interface StationResult { diva:string; name:string }
export default function WienSettingsPanel({settings,onChange,onClose}:{settings:WienSettings;onChange:(settings:WienSettings)=>void;onClose:()=>void}) {
  const [draft,setDraft]=useState(settings); const [query,setQuery]=useState(''); const [stations,setStations]=useState<StationResult[]>([]); const [searching,setSearching]=useState(false)
  useEffect(()=>{if(query.trim().length<2){setStations([]);return}const controller=new AbortController();const timer=setTimeout(async()=>{setSearching(true);try{const response=await fetch(`/api/wien/transit/stations?q=${encodeURIComponent(query)}`,{signal:controller.signal});const data=await response.json();setStations(data.stations||[])}catch(error){if((error as Error).name!=='AbortError')setStations([])}finally{setSearching(false)}},350);return()=>{clearTimeout(timer);controller.abort()}},[query])
  const addFavorite=(station:StationResult)=>{if(draft.favorites.length>=6||draft.favorites.some(item=>item.diva===station.diva))return;setDraft({...draft,favorites:[...draft.favorites,{diva:station.diva,name:station.name,line:'U2',direction:'both'}]});setQuery('');setStations([])}
  const moveFavorite=(from:number,to:number)=>{const next=[...draft.favorites];const [item]=next.splice(from,1);next.splice(to,0,item);setDraft({...draft,favorites:next})}
  return <div className="wien-settings-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><aside className="wien-settings" role="dialog" aria-modal="true" aria-labelledby="wien-settings-title"><header><div><span className="wien-eyebrow">WIEN LIVE</span><h2 id="wien-settings-title">Einstellungen</h2></div><button onClick={onClose} aria-label="Einstellungen schließen">×</button></header><div className="settings-scroll">
    <section><h3>U-Bahn-Favoriten</h3><p>Donaumarina bleibt immer fixiert. Bis zu sechs weitere Stationen.</p><label className="settings-field"><span>Haltestelle suchen</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="z. B. Praterstern"/></label>{searching&&<small>Suche …</small>}{stations.length>0&&<div className="station-results">{stations.map(station=><button key={station.diva} onClick={()=>addFavorite(station)}>{station.name}<small>{station.diva}</small></button>)}</div>}<div className="favorite-list"><div className="favorite fixed"><span>↕</span><strong>U2 Donaumarina</strong><em>Fixiert</em></div>{draft.favorites.map((favorite,index)=><div className="favorite" key={favorite.diva} draggable onDragStart={e=>e.dataTransfer.setData('text/plain',String(index))} onDragOver={e=>e.preventDefault()} onDrop={e=>moveFavorite(Number(e.dataTransfer.getData('text/plain')),index)}><span>↕</span><strong>{favorite.name}</strong><select value={favorite.line} aria-label={`Linie für ${favorite.name}`} onChange={e=>{const next=[...draft.favorites];next[index]={...favorite,line:e.target.value};setDraft({...draft,favorites:next})}}><option>U1</option><option>U2</option><option>U3</option><option>U4</option><option>U6</option></select><select value={favorite.direction} aria-label={`Fahrtrichtung für ${favorite.name}`} onChange={e=>{const next=[...draft.favorites];next[index]={...favorite,direction:e.target.value};setDraft({...draft,favorites:next})}}><option value="both">Beide</option><option value="H">Hin</option><option value="R">Retour</option></select><button onClick={()=>setDraft({...draft,favorites:draft.favorites.filter(item=>item.diva!==favorite.diva)})} aria-label={`${favorite.name} entfernen`}>×</button></div>)}</div></section>
    <section><h3>Route Tangente</h3><div className="settings-grid"><label className="settings-field"><span>Startadresse</span><input value={draft.trafficStart} onChange={e=>setDraft({...draft,trafficStart:e.target.value})}/></label><label className="settings-field"><span>Zieladresse</span><input value={draft.trafficDestination} onChange={e=>setDraft({...draft,trafficDestination:e.target.value})}/></label><label className="settings-field"><span>Bevorzugte Route</span><input value={draft.preferredRoute} onChange={e=>setDraft({...draft,preferredRoute:e.target.value})}/></label><label className="settings-field"><span>Intervall (Sek.)</span><input type="number" min="120" max="900" value={draft.trafficInterval} onChange={e=>setDraft({...draft,trafficInterval:Number(e.target.value)})}/></label></div><label className="toggle"><input type="checkbox" checked={draft.motorways} onChange={e=>setDraft({...draft,motorways:e.target.checked})}/> Autobahn verwenden</label><label className="toggle"><input type="checkbox" checked={draft.tollRoads} onChange={e=>setDraft({...draft,tollRoads:e.target.checked})}/> Mautstraßen erlauben</label></section>
    <section><h3>Wetter & Events</h3><div className="settings-grid"><label className="settings-field"><span>Breitengrad</span><input type="number" step=".0001" value={draft.weatherLat} onChange={e=>setDraft({...draft,weatherLat:Number(e.target.value)})}/></label><label className="settings-field"><span>Längengrad</span><input type="number" step=".0001" value={draft.weatherLon} onChange={e=>setDraft({...draft,weatherLon:Number(e.target.value)})}/></label><label className="settings-field"><span>Eventradius (km)</span><input type="number" min="1" max="50" value={draft.eventRadius} onChange={e=>setDraft({...draft,eventRadius:Number(e.target.value)})}/></label></div><div className="category-chips">{['Konzerte','Theater','Film','Ausstellung','Festival','Club','Kostenlos'].map(category=><button className={draft.eventCategories.includes(category)?'active':''} onClick={()=>setDraft({...draft,eventCategories:draft.eventCategories.includes(category)?draft.eventCategories.filter(item=>item!==category):[...draft.eventCategories,category]})} key={category}>{category}</button>)}</div></section>
    <section><h3>Darstellung & Aktualisierung</h3><label className="toggle"><input type="checkbox" checked={draft.autoRefresh} onChange={e=>setDraft({...draft,autoRefresh:e.target.checked})}/> Automatisch aktualisieren</label><div className="settings-grid"><label className="settings-field"><span>U-Bahn (Sek.)</span><input type="number" min="20" max="120" value={draft.transitInterval} onChange={e=>setDraft({...draft,transitInterval:Number(e.target.value)})}/></label><label className="settings-field"><span>Wetter (Sek.)</span><input type="number" min="600" max="3600" value={draft.weatherInterval} onChange={e=>setDraft({...draft,weatherInterval:Number(e.target.value)})}/></label><label className="settings-field"><span>Events (Sek.)</span><input type="number" min="1800" max="7200" value={draft.eventsInterval} onChange={e=>setDraft({...draft,eventsInterval:Number(e.target.value)})}/></label><label className="settings-field"><span>Zeitformat</span><select value={draft.hourFormat} onChange={e=>setDraft({...draft,hourFormat:e.target.value as '12'|'24'})}><option value="24">24 Stunden</option><option value="12">12 Stunden</option></select></label><label className="settings-field"><span>Darstellung</span><select value={draft.density} onChange={e=>setDraft({...draft,density:e.target.value as 'compact'|'large'})}><option value="compact">Kompakt</option><option value="large">Groß</option></select></label></div></section>
    </div><footer><button className="settings-cancel" onClick={onClose}>Abbrechen</button><button className="settings-save" onClick={()=>{onChange(draft);onClose()}}>Speichern</button></footer></aside></div>
}
